version: "3"

vars:
  CLUSTER_NAME: demo-cluster
  NAMESPACE: demo-app

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup:
    desc: Setup the demo environment
    cmds:
      - echo "Setting up FluxCD and Flagger demo environment..."
      - task: check-tools

  check-tools:
    desc: Verify required tools are installed
    cmds:
      - kubectl version --client
      - helm version
      - flux version --client
      - k3d version

  cluster:create:
    desc: Create a local Kubernetes cluster using k3d
    cmds:
      - echo "Creating k3d cluster{{":"}} {{.CLUSTER_NAME}}"
      - k3d cluster create --config k3d-config.yaml
      - kubectl cluster-info

  cluster:delete:
    desc: Delete the k3d cluster
    cmds:
      - echo "Deleting k3d cluster{{":"}} {{.CLUSTER_NAME}}"
      - k3d cluster delete {{.CLUSTER_NAME}}

  flux:install:
    desc: Install Flux using the flux operator
    cmds:
      - echo "Installing Flux operator..."
      - helm install flux-operator oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator --namespace flux-system --create-namespace
      - echo "Waiting for Flux operator to be ready..."
      - kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=flux-operator -n flux-system --timeout=300s

  flux:configure:
    desc: Create FluxInstance to configure Flux controllers
    cmds:
      - echo "Creating FluxInstance configuration..."
      - kubectl apply -f cluster-init/flux-instance.yaml
      - echo "Waiting for Flux controllers to be ready..."
      - kubectl wait --for=condition=ready pod -l app=source-controller -n flux-system --timeout=300s

  flagger:install:
    desc: Install Flagger with Prometheus
    cmds:
      - echo "Installing Flagger..."
      - helm repo add flagger https://flagger.app
      - helm repo update
      - helm upgrade -i flagger flagger/flagger --namespace=flagger-system --create-namespace --set prometheus.install=true

  demo:setup:
    desc: Setup complete demo environment
    deps: [setup, cluster:create, flux:install, flux:configure, flagger:install]
    cmds:
      - echo "Demo environment setup complete!"
      - echo "Cluster{{":"}} {{.CLUSTER_NAME}}"
      - echo "Flux and Flagger are ready for use"

  demo:canary:
    desc: Demonstrate canary deployment
    cmds:
      - echo "Deploying canary release..."
      - echo "kubectl apply -f manifests/canary.yaml"

  demo:rollback:
    desc: Demonstrate automated rollback
    cmds:
      - echo "Triggering rollback scenario..."
      - echo "kubectl patch canary demo-app -p '{\"spec\":{\"analysis\":{\"threshold\":1}}}'"

  status:
    desc: Check status of demo components
    cmds:
      - echo "=== Cluster Status ==="
      - kubectl cluster-info
      - echo ""
      - echo "=== Flux Status ==="
      - kubectl get pods -n flux-system
      - echo ""
      - echo "=== Flagger Status ==="
      - kubectl get pods -n flagger-system

  clean:
    desc: Clean up demo resources
    cmds:
      - echo "Cleaning up demo resources..."
      - kubectl delete namespace {{.NAMESPACE}} --ignore-not-found=true
      - task: cluster:delete
