apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/riccap/demo-cnd-italy-2025
  ref:
    branch: main
  secretRef:
    name: ghcr-auth