apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger-loadtester
  namespace: nginx-demo
spec:
  interval: 1h
  chart:
    spec:
      chart: loadtester
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
      interval: 1h
  values:
    nameOverride: "loadtester"
    fullnameOverride: "flagger-loadtester"
    replicaCount: 1
    image:
      repository: ghcr.io/fluxcd/flagger-loadtester
      tag: latest
    service:
      type: ClusterIP
      port: 8080
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi