apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: flagger
      version: "1.37.0"
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
      interval: 1m
  targetNamespace: flagger-system
  createNamespace: true
  values:
    meshProvider: kubernetes
    metricsServer: http://prometheus:9090
    slack:
      url: ""
      channel: ""
      username: flagger