apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./demo"
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo-repo
  wait: true
  timeout: 5m
