apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-kustomization.yaml
  - nginx-helm-repository.yaml
  - nginx-helm-release.yaml
  - demo-git-repository.yaml
  - flagger-helm-repository.yaml
  - flagger-loadtester-helm-release.yaml
