apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "~4.8.0"
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
      interval: 5m
  targetNamespace: nginx-ingress
  install:
    createNamespace: true
  values:
    controller:
      service:
        type: LoadBalancer
      admissionWebhooks:
        enabled: true
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
    defaultBackend:
      enabled: false