apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - canary.yaml

commonLabels:
  app: nginx

namePrefix: demo-

images:
  - name: nginx
    newTag: latest